[theme]
base="dark"
primaryColor="#228B22"
backgroundColor="#0E1117"
secondaryBackgroundColor="darkSeaGreen"
textColor="#FAFAFA"
font="sans serif"
baseRadius="large"

[theme.sidebar]
primaryColor="#228B22"